services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bot:
    build:
      dockerfile: packages/bot/Dockerfile
    env_file: ".env"
    ports:
      - "33250:33250"
    depends_on:
      - database
      - api
  client:
    build:
      dockerfile: packages/web/Dockerfile
    env_file: ".env"
    ports:
      - "33251:33251"
    depends_on:
      - database
      - api
  api:
    build: ./packages/api
    env_file: ".env"
    ports:
      - "33252:33252"
    depends_on:
      - database
