services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  bot:
    build: .
    env_file: ".env"
    ports:
      - "3000:3000"
    depends_on:
      - database
